import { Report } from '../types/report';

export const mockReports: Report[] = [
  {
    id: 'RPT-1001',
    title: 'Burst Water Pipe on Fatih Sultan Mehmet Blvd',
    description: 'There is a massive water leak flowing into the street near the intersection. It started about an hour ago and is getting worse.',
    latitude: 40.2173,
    longitude: 28.9892,
    category: 'Water & Plumbing',
    department: 'BUSKI',
    riskScore: 85,
    priority: 'critical',
    status: 'in_review',
    aiSummary: 'Major water leakage from a burst pipe on a main boulevard causing potential traffic hazards and water waste.',
    recommendedAction: 'Dispatch emergency plumbing unit immediately to shut off the main valve and repair the pipe.',
    createdAt: '2026-04-20T08:15:00Z',
    updatedAt: '2026-04-20T08:45:00Z',
  },
  {
    id: 'RPT-1002',
    title: 'Sewage Overflow near Kültürpark',
    description: 'Bad smell and sewage coming out of the manhole cover next to the park entrance.',
    latitude: 40.1932,
    longitude: 29.0435, // Bursa Kültürpark area
    category: 'Sanitation',
    department: 'BUSKI',
    riskScore: 78,
    priority: 'high',
    status: 'pending',
    aiSummary: 'Sewage overflow near a public park creating health risks and severe odor.',
    recommendedAction: 'Send vacuum truck and sanitation crew to clear the blockage and clean the area.',
    createdAt: '2026-04-23T14:30:00Z',
    updatedAt: '2026-04-23T14:30:00Z',
  },
  {
    id: 'RPT-1003',
    title: 'Deep Pothole in Osmangazi',
    description: 'Very deep pothole on the right lane. Several cars have hit it and it might cause an accident.',
    latitude: 40.1824,
    longitude: 29.0655,
    category: 'Infrastructure',
    department: 'Department of Transportation',
    riskScore: 65,
    priority: 'medium',
    status: 'resolved',
    aiSummary: 'A dangerous pothole in a traffic lane causing potential vehicular damage.',
    recommendedAction: 'Schedule road maintenance team for asphalt patching.',
    createdAt: '2026-04-18T10:20:00Z',
    updatedAt: '2026-04-21T09:10:00Z',
  },
  {
    id: 'RPT-1004',
    title: 'Fallen Tree Blocking Road in Setbaşı',
    description: 'A large tree fell down during the storm last night and is completely blocking the road.',
    latitude: 40.1812,
    longitude: 29.0701,
    category: 'Emergency',
    department: 'Parks and Gardens',
    riskScore: 92,
    priority: 'critical',
    status: 'pending',
    aiSummary: 'Fallen tree obstructing a critical local roadway after a storm, blocking traffic.',
    recommendedAction: 'Emergency dispatch for tree removal and traffic redirection.',
    createdAt: '2026-04-24T06:05:00Z',
    updatedAt: '2026-04-24T06:15:00Z',
  },
  {
    id: 'RPT-1005',
    title: 'Broken Sidewalk in Nilüfer',
    description: 'The pavement tiles are completely shattered here, making it dangerous for pedestrians and impossible for wheelchairs.',
    latitude: 40.2105,
    longitude: 28.9450,
    category: 'Infrastructure',
    department: 'Public Works',
    riskScore: 45,
    priority: 'low',
    status: 'in_review',
    aiSummary: 'Shattered pavement tiles obstructing pedestrian and wheelchair mobility.',
    recommendedAction: 'Schedule routine sidewalk repair.',
    createdAt: '2026-04-21T11:00:00Z',
    updatedAt: '2026-04-22T10:00:00Z',
  },
  {
    id: 'RPT-1006',
    title: 'Garbage Accumulation in Yıldırım',
    description: 'The dumpsters have not been emptied for days and trash is piling up on the streets.',
    latitude: 40.1950,
    longitude: 29.0980,
    category: 'Sanitation',
    department: 'Waste Management',
    riskScore: 55,
    priority: 'medium',
    status: 'pending',
    aiSummary: 'Uncollected garbage accumulating around dumpsters causing sanitation concerns.',
    recommendedAction: 'Dispatch waste collection truck to the overflow location.',
    createdAt: '2026-04-24T18:00:00Z',
    updatedAt: '2026-04-24T18:00:00Z',
  },
  {
    id: 'RPT-1007',
    title: 'Flooded Underpass after Heavy Rain',
    description: 'The underpass near the metro station is fully flooded. Cars cannot pass through.',
    latitude: 40.1983,
    longitude: 28.9954,
    category: 'Emergency',
    department: 'Buski & Transportation',
    riskScore: 88,
    priority: 'critical',
    status: 'resolved',
    aiSummary: 'Metro station underpass heavily flooded and impassable for vehicles.',
    recommendedAction: 'Deploy water pumping units and clear drainage systems.',
    createdAt: '2026-04-15T07:30:00Z',
    updatedAt: '2026-04-15T15:00:00Z',
  },
  {
    id: 'RPT-1008',
    title: 'Broken Streetlights in Görükle',
    description: 'An entire street has had no working streetlights for the past 3 nights.',
    latitude: 40.2255,
    longitude: 28.8500,
    category: 'Electrical',
    department: 'UEDAŞ',
    riskScore: 60,
    priority: 'medium',
    status: 'in_review',
    aiSummary: 'A stretch of street is completely dark due to non-functioning streetlights, posing safety risks.',
    recommendedAction: 'Check electrical grid for local failure and replace broken bulbs.',
    createdAt: '2026-04-22T20:15:00Z',
    updatedAt: '2026-04-23T09:00:00Z',
  },
  {
    id: 'RPT-1009',
    title: 'Traffic Sign Fallen in Mudanya',
    description: 'The stop sign at the intersection blew over and is lying on the ground.',
    latitude: 40.3705,
    longitude: 28.8821,
    category: 'Traffic',
    department: 'Department of Transportation',
    riskScore: 40,
    priority: 'low',
    status: 'pending',
    aiSummary: 'Stop sign blown over at an intersection, potentially causing traffic confusion.',
    recommendedAction: 'Dispatch crew to re-install traffic sign.',
    createdAt: '2026-04-25T08:12:00Z',
    updatedAt: '2026-04-25T08:12:00Z',
  },
  {
    id: 'RPT-1010',
    title: 'Graffiti on Historical Monument',
    description: 'Someone spray-painted on the walls of the historical tomb complex.',
    latitude: 40.1843,
    longitude: 29.0718, // Green Tomb general area
    category: 'Vandalism',
    department: 'Cultural Heritage',
    riskScore: 70,
    priority: 'high',
    status: 'in_review',
    aiSummary: 'Vandalism via graffiti on a historical monument requiring specialized cleaning.',
    recommendedAction: 'Send specialized historical preservation team for damage-free cleaning.',
    createdAt: '2026-04-23T10:45:00Z',
    updatedAt: '2026-04-24T11:00:00Z',
  }
];
